SQL> SELECT customer_id,customer_name,customer_category,customer_address,customer_mail_address,customer_phone_number
  2  FROM Customer
  3  ORDER BY customer_category;

CUSTOMER_I CUSTOMER_NAME        CUSTOMER_CATEGORY    CUSTOMER_ADDRESS                                   CUSTOMER_MAIL_ADDRESS                              CUSTOMER_PHONE_NUMBE                                                                                                                                                                                                                                                                                                                                     
---------- -------------------- -------------------- -------------------------------------------------- -------------------------------------------------- --------------------                                                                                                                                                                                                                                                                                                                                     
C005       Prayas Basnet        Loyal                Kathmandu,Nepal                                    prayas@gmail.com                                   (555)557-1234                                                                                                                                                                                                                                                                                                                                            
C010       Amit Sharma          Loyal                Amsterdam,Netherlands                              amit@gmail.com                                     (555)557-1239                                                                                                                                                                                                                                                                                                                                            
C002       Anjel Aryal          Loyal                Berlin,Germany                                     anjel@gmail.com                                    (555)557-1231                                                                                                                                                                                                                                                                                                                                            
C004       Samita Sunuwar       Priviledged          Boston,USA                                         samita@gmail.com                                   (555)557-1233                                                                                                                                                                                                                                                                                                                                            
C009       Rijan Kafle          Priviledged          Chicagp,USA                                        rijan@gmail.com                                    (555)557-1238                                                                                                                                                                                                                                                                                                                                            
C003       Jeena Dahal          Regular              Malibu,USA                                         jeena@gmail.com                                    (555)557-1232                                                                                                                                                                                                                                                                                                                                            
C008       Bibhor Bhattarai     Regular              Sydney,Australia                                   bibhor@gmail.com                                   (555)557-1237                                                                                                                                                                                                                                                                                                                                            
C001       Baibhab Bhattarai    Regular              San Fransico,USA                                   baibhab@gmail.com                                  (555)557-1230                                                                                                                                                                                                                                                                                                                                            
C006       Sahara Gartaula      VIP                  San Fransico,USA                                   sahara@gmail.com                                   (555)557-1235                                                                                                                                                                                                                                                                                                                                            
C007       Yubaraj Dhakal       VIP                  Madrid,Spain                                       yubaraj@gmail.com                                  (555)557-1236                                                                                                                                                                                                                                                                                                                                            

10 rows selected.

SQL> spool off
