SQL> SELECT painting_id,painting_name,artist.artist_name,rent_price,(20/100)*rent_price AS "PAID_PRICE"
  2  FROM Painting,Artist
  3  WHERE Painting.artist_id=Artist.artist_id;

PAINTING_I PAINTING_NAME                                      ARTIST_NAME                                        RENT_PRICE PAID_PRICE                                                                                                                                                                                                                                                                                                                                                                              
---------- -------------------------------------------------- -------------------------------------------------- ---------- ----------                                                                                                                                                                                                                                                                                                                                                                              
P001       Guernica                                           Pablo Picasa                                             3200        640                                                                                                                                                                                                                                                                                                                                                                              
P002       Monalisa                                           Leonardo Da Vinci                                        2500        500                                                                                                                                                                                                                                                                                                                                                                              
P003       Starry Nights                                      Van Gogh                                                 6200       1240                                                                                                                                                                                                                                                                                                                                                                              
P004       The Elephants                                      Salvador Dali                                            5500       1100                                                                                                                                                                                                                                                                                                                                                                              
P005       Girl With a Pearl Earring                          Johannes Vermeer                                         8000       1600                                                                                                                                                                                                                                                                                                                                                                              
P006       Gold Fish                                          Henri Matisse                                            3100        620                                                                                                                                                                                                                                                                                                                                                                              
P007       Mural                                              Jackson Pollock                                          5000       1000                                                                                                                                                                                                                                                                                                                                                                              
P008       Samson and Delilah                                 Peter Paul Rubens                                        7500       1500                                                                                                                                                                                                                                                                                                                                                                              
P009       The Last Supper                                    Leonardo Da Vinci                                        9000       1800                                                                                                                                                                                                                                                                                                                                                                              
P010       Blue Nudes                                         Henri Matisse                                            5000       1000                                                                                                                                                                                                                                                                                                                                                                              
P011       The Milk Maid                                      Johannes Vermeer                                         6000       1200                                                                                                                                                                                                                                                                                                                                                                              
P012       Almond Blossoms                                    Van Gogh                                                 8000       1600                                                                                                                                                                                                                                                                                                                                                                              
P013       The Mountains                                      Leonardo Da Vinci                                        8500       1700                                                                                                                                                                                                                                                                                                                                                                              
P014       The Mask                                           Johannes Vermeer                                         7000       1400                                                                                                                                                                                                                                                                                                                                                                              
P015       Cherry Springs                                     Peter Paul Rubens                                        6000       1200                                                                                                                                                                                                                                                                                                                                                                              
P016       Night Sky                                          Henri Matisse                                            5000       1000                                                                                                                                                                                                                                                                                                                                                                              
P017       Naked                                              Pablo Picasa                                             9000       1800                                                                                                                                                                                                                                                                                                                                                                              
P018       Unicorn                                            Salvador Dali                                            5500       1100                                                                                                                                                                                                                                                                                                                                                                              

18 rows selected.

SQL> spool off
