SQL> SELECT * FROM Staff ORDER BY annual_salary DESC;

STAFF_ID   STAFF_NAME                                         STAFF_MAIL_ADDRESS                                           STAFF_PHONE_NUMBER   ANNUAL_SALARY                                                                                                                                                                                                                                                                                                                                                       
---------- -------------------------------------------------- ------------------------------------------------------------ -------------------- -------------                                                                                                                                                                                                                                                                                                                                                       
S05        Hannah Baker                                       hannahb@gmail.com                                            (555)555-1238                69000                                                                                                                                                                                                                                                                                                                                                       
S07        Bruce Wayne                                        brucew@gmail.com                                             (555)555-1230                56000                                                                                                                                                                                                                                                                                                                                                       
S04        Clay Jensen                                        clayj@gmail.com                                              (555)555-1237                47000                                                                                                                                                                                                                                                                                                                                                       
S02        Mary Jane                                          maryj@gmail.com                                              (555)555-1235                45000                                                                                                                                                                                                                                                                                                                                                       
S03        Peter McKenzie                                     peterm@gmail.com                                             (555)555-1236                41000                                                                                                                                                                                                                                                                                                                                                       
S01        John David                                         johnd@gmail.com                                              (555)555-1234                40000                                                                                                                                                                                                                                                                                                                                                       
S06        Noah Parker                                        noahp@gmail.com                                              (555)555-1239                27000                                                                                                                                                                                                                                                                                                                                                       

7 rows selected.

SQL> spool off
