SQL> SELECT Customer.customer_id,Customer.customer_name,Painting.painting_name,Transaction.transaction_date
  2  FROM Customer,PaintingLeased,Painting,Transaction
  3  WHERE Customer.customer_id = PaintingLeased.customer_id AND
  4  Painting.painting_id=PaintingLeased.painting_id AND
  5  Transaction.transaction_id=Customer.transaction_id AND Customer.customer_id = 'C001';

CUSTOMER_I CUSTOMER_NAME        PAINTING_NAME                                      TRANSACTI                                                                                                                                                                                                                                                                                                                                                                                                                        
---------- -------------------- -------------------------------------------------- ---------                                                                                                                                                                                                                                                                                                                                                                                                                        
C001       Baibhab Bhattarai    Guernica                                           14-DEC-21                                                                                                                                                                                                                                                                                                                                                                                                                        
C001       Baibhab Bhattarai    Monalisa                                           14-DEC-21                                                                                                                                                                                                                                                                                                                                                                                                                        
C001       Baibhab Bhattarai    The Elephants                                      14-DEC-21                                                                                                                                                                                                                                                                                                                                                                                                                        
C001       Baibhab Bhattarai    Gold Fish                                          14-DEC-21                                                                                                                                                                                                                                                                                                                                                                                                                        
C001       Baibhab Bhattarai    Mural                                              14-DEC-21                                                                                                                                                                                                                                                                                                                                                                                                                        
C001       Baibhab Bhattarai    Unicorn                                            14-DEC-21                                                                                                                                                                                                                                                                                                                                                                                                                        

6 rows selected.

SQL> spool off
