SQL> SELECT painting_id,painting_name FROM Painting
  2  WHERE return_status = 'Returned';

PAINTING_I PAINTING_NAME                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
---------- --------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                       
P001       Guernica                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
P002       Monalisa                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
P004       The Elephants                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
P006       Gold Fish                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
P007       Mural                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
P008       Samson and Delilah                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
P009       The Last Supper                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
P011       The Milk Maid                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
P012       Almond Blossoms                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
P013       The Mountains                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
P014       The Mask                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
P015       Cherry Springs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
P016       Night Sky                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
P017       Naked                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
P018       Unicorn                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

15 rows selected.

SQL> spool off
