SQL> SELECT * FROM Painting
  2  WHERE (SYSDATE - last_leased_date) >= 90;

PAINTING_I ARTIST_ID  OWNER_ID   PAINTING_NAME                                      PAINTING_CATEGORY    RENT_PRICE AVAILABLE_STATUS     RETURN_STATUS        LAST_LEAS ISSUE_DAT                                                                                                                                                                                                                                                                                                                                   
---------- ---------- ---------- -------------------------------------------------- -------------------- ---------- -------------------- -------------------- --------- ---------                                                                                                                                                                                                                                                                                                                                   
P001       A003       O001       Guernica                                           Landscape                  3200 Available            Returned             15-SEP-21 10-AUG-21                                                                                                                                                                                                                                                                                                                                   
P004       A008       O007       The Elephants                                      Animal                     5500 Available            Returned             01-JUN-21 20-APR-21                                                                                                                                                                                                                                                                                                                                   
P007       A006       O002       Mural                                              Landscape                  5000 Available            Returned             10-JUN-21 06-MAR-21                                                                                                                                                                                                                                                                                                                                   
P014       A007       O005       The Mask                                           Person                     7000 Available            Returned             18-AUG-21 10-MAR-21                                                                                                                                                                                                                                                                                                                                   
P015       A005       O001       Cherry Springs                                     Landscape                  6000 Available            Returned             12-FEB-21 10-NOV-21                                                                                                                                                                                                                                                                                                                                   
P016       A004       O003       Night Sky                                          Landscape                  5000 Available            Returned             25-JAN-21 19-JAN-21                                                                                                                                                                                                                                                                                                                                   

6 rows selected.

SQL> spool off
