SQL> SELECT painting_id,painting_name,CAST((((
  2  last_leased_date - issue_date)/30)*rent_price) AS INT) AS "COLLECTED RENT AMOUNT"
  3  FROM Painting
  4  WHERE rownum <= 5
  5  ORDER BY "COLLECTED RENT AMOUNT" DESC;

PAINTING_I PAINTING_NAME                                      COLLECTED RENT AMOUNT                                                                                                                                                                                                                                                                                                                                                                                                                                 
---------- -------------------------------------------------- ---------------------                                                                                                                                                                                                                                                                                                                                                                                                                                 
P005       Girl With a Pearl Earring                                         187467                                                                                                                                                                                                                                                                                                                                                                                                                                 
P004       The Elephants                                                       7700                                                                                                                                                                                                                                                                                                                                                                                                                                 
P001       Guernica                                                            3840                                                                                                                                                                                                                                                                                                                                                                                                                                 
P002       Monalisa                                                            3083                                                                                                                                                                                                                                                                                                                                                                                                                                 
P003       Starry Nights                                                        413                                                                                                                                                                                                                                                                                                                                                                                                                                 

SQL> spool off
