SQL> SELECT Painting.artist_id,Artist.artist_name,
  2  SUM(rent_price) AS "PAINTING SOLD VALUE TOTAL"
  3  FROM Painting,Artist
  4  WHERE Painting.artist_id = Artist.artist_id
  5  AND((SYSDATE-last_leased_date)<30)
  6  GROUP BY Painting.artist_id,artist.Artist_name;

ARTIST_ID  ARTIST_NAME                                        PAINTING SOLD VALUE TOTAL                                                                                                                                                                                                                                                                                                                                                                                                                             
---------- -------------------------------------------------- -------------------------                                                                                                                                                                                                                                                                                                                                                                                                                             
A002       Van Gogh                                                               14200                                                                                                                                                                                                                                                                                                                                                                                                                             
A004       Henri Matisse                                                           5000                                                                                                                                                                                                                                                                                                                                                                                                                             
A008       Salvador Dali                                                           5500                                                                                                                                                                                                                                                                                                                                                                                                                             
A007       Johannes Vermeer                                                        8000                                                                                                                                                                                                                                                                                                                                                                                                                             
A001       Leonardo Da Vinci                                                      11000                                                                                                                                                                                                                                                                                                                                                                                                                             

SQL> spool off
